# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 109455308bd39af35a58ed0012b404a056e66eeebd0356a0d414695b5af5497ee101e518a8cc7b1bffdda9913f56cb34f0eaec6769abaab06a8a9f463c39e1dc

test:
  secret_key_base: d4e0547019599e76ef2fc782370874dce1a35532746c535aa3591860aa21203b9e726c737ce8320b92dad4ee07c70c1fdb76f262f41b7eed1dbcfdba902443e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
